// Generated by scripts/gen-flow.mjs from src/cfd/flow.js - do not edit.
// Collision models of the v1 flow engine (flow.wgsl): post-collision populations in place,
// returning (rho, ux, uy, uz).

fn collide_rr(f: ptr<function, array<f32, 19>>, tau0: f32, smag: f32, tauMin: f32) -> vec4<f32> {
  var f0 = (*f)[0];
  var f1 = (*f)[1];
  var f2 = (*f)[2];
  var f3 = (*f)[3];
  var f4 = (*f)[4];
  var f5 = (*f)[5];
  var f6 = (*f)[6];
  var f7 = (*f)[7];
  var f8 = (*f)[8];
  var f9 = (*f)[9];
  var f10 = (*f)[10];
  var f11 = (*f)[11];
  var f12 = (*f)[12];
  var f13 = (*f)[13];
  var f14 = (*f)[14];
  var f15 = (*f)[15];
  var f16 = (*f)[16];
  var f17 = (*f)[17];
  var f18 = (*f)[18];
  let rho = f0 + f1 + f2 + f3 + f4 + f5 + f6 + f7 + f8 + f9 + f10 + f11 + f12 + f13 + f14 + f15 + f16 + f17 + f18;
  let ir = 1.0 / rho;
  let ux = (f1 + f7 + f9 + f11 + f13 - f2 - f8 - f10 - f12 - f14) * ir;
  let uy = (f3 + f7 + f10 + f15 + f17 - f4 - f8 - f9 - f16 - f18) * ir;
  let uz = (f5 + f11 + f14 + f15 + f18 - f6 - f12 - f13 - f16 - f17) * ir;
  let nxx = f1 + f2 + f7 + f8 + f9 + f10 + f11 + f12 + f13 + f14 - rho * (ux * ux + 0.333333333333333);
  let nyy = f3 + f4 + f7 + f8 + f9 + f10 + f15 + f16 + f17 + f18 - rho * (uy * uy + 0.333333333333333);
  let nzz = f5 + f6 + f11 + f12 + f13 + f14 + f15 + f16 + f17 + f18 - rho * (uz * uz + 0.333333333333333);
  let nxy = f7 + f8 - f9 - f10 - rho * ux * uy;
  let nxz = f11 + f12 - f13 - f14 - rho * ux * uz;
  let nyz = f15 + f16 - f17 - f18 - rho * uy * uz;
  let qn = sqrt(nxx * nxx + nyy * nyy + nzz * nzz + 2.0 * (nxy * nxy + nxz * nxz + nyz * nyz));
  let tau = max(0.5 * (tau0 + sqrt(tau0 * tau0 + smag * qn * ir)), tauMin);
  let om = 1.0 / tau;
  let usq = 1.5 * (ux * ux + uy * uy + uz * uz);
  let k = 1.0 - om;
  let a0p1 = ux * ux * uy + uy * uz * uz;
  let a0p2 = ux * uz * uz + ux * uy * uy;
  let a0p3 = uy * uy * uz + ux * ux * uz;
  let a0m1 = ux * ux * uy - uy * uz * uz;
  let a0m2 = ux * uz * uz - ux * uy * uy;
  let a0m3 = uy * uy * uz - ux * ux * uz;
  let txxy = 2.0 * ux * nxy + uy * nxx;
  let tyzz = 2.0 * uz * nyz + uy * nzz;
  let txzz = 2.0 * uz * nxz + ux * nzz;
  let txyy = 2.0 * uy * nxy + ux * nyy;
  let tyyz = 2.0 * uy * nyz + uz * nyy;
  let txxz = 2.0 * ux * nxz + uz * nxx;
  let a1p1 = txxy + tyzz;
  let a1p2 = txzz + txyy;
  let a1p3 = tyyz + txxz;
  let a1m1 = txxy - tyzz;
  let a1m2 = txzz - txyy;
  let a1m3 = tyyz - txxz;
  let tr = 0.333333333333333 * (nxx + nyy + nzz);
  f0 = 0.333333333333333 * (rho * (1.0 - usq) + k * (4.5 * (-tr)));
  let cu1 = ux;
  f1 = 0.0555555555555556 * (rho * (1.0 + 3.0 * cu1 + 4.5 * cu1 * cu1 - usq - 9.0 * a0p2) + k * (4.5 * (nxx - tr) - 9.0 * a1p2));
  let cu2 = -ux;
  f2 = 0.0555555555555556 * (rho * (1.0 + 3.0 * cu2 + 4.5 * cu2 * cu2 - usq + 9.0 * a0p2) + k * (4.5 * (nxx - tr) + 9.0 * a1p2));
  let cu3 = uy;
  f3 = 0.0555555555555556 * (rho * (1.0 + 3.0 * cu3 + 4.5 * cu3 * cu3 - usq - 9.0 * a0p1) + k * (4.5 * (nyy - tr) - 9.0 * a1p1));
  let cu4 = -uy;
  f4 = 0.0555555555555556 * (rho * (1.0 + 3.0 * cu4 + 4.5 * cu4 * cu4 - usq + 9.0 * a0p1) + k * (4.5 * (nyy - tr) + 9.0 * a1p1));
  let cu5 = uz;
  f5 = 0.0555555555555556 * (rho * (1.0 + 3.0 * cu5 + 4.5 * cu5 * cu5 - usq - 9.0 * a0p3) + k * (4.5 * (nzz - tr) - 9.0 * a1p3));
  let cu6 = -uz;
  f6 = 0.0555555555555556 * (rho * (1.0 + 3.0 * cu6 + 4.5 * cu6 * cu6 - usq + 9.0 * a0p3) + k * (4.5 * (nzz - tr) + 9.0 * a1p3));
  let cu7 = ux + uy;
  f7 = 0.0277777777777778 * (rho * (1.0 + 3.0 * cu7 + 4.5 * cu7 * cu7 - usq + 4.5 * a0p1 + 4.5 * a0p2 + 4.5 * a0m1 - 4.5 * a0m2) + k * (4.5 * (nxx + nyy + 2.0 * nxy - tr) + 4.5 * a1p1 + 4.5 * a1p2 + 4.5 * a1m1 - 4.5 * a1m2));
  let cu8 = -ux - uy;
  f8 = 0.0277777777777778 * (rho * (1.0 + 3.0 * cu8 + 4.5 * cu8 * cu8 - usq - 4.5 * a0p1 - 4.5 * a0p2 - 4.5 * a0m1 + 4.5 * a0m2) + k * (4.5 * (nxx + nyy + 2.0 * nxy - tr) - 4.5 * a1p1 - 4.5 * a1p2 - 4.5 * a1m1 + 4.5 * a1m2));
  let cu9 = ux - uy;
  f9 = 0.0277777777777778 * (rho * (1.0 + 3.0 * cu9 + 4.5 * cu9 * cu9 - usq - 4.5 * a0p1 + 4.5 * a0p2 - 4.5 * a0m1 - 4.5 * a0m2) + k * (4.5 * (nxx + nyy - 2.0 * nxy - tr) - 4.5 * a1p1 + 4.5 * a1p2 - 4.5 * a1m1 - 4.5 * a1m2));
  let cu10 = -ux + uy;
  f10 = 0.0277777777777778 * (rho * (1.0 + 3.0 * cu10 + 4.5 * cu10 * cu10 - usq + 4.5 * a0p1 - 4.5 * a0p2 + 4.5 * a0m1 + 4.5 * a0m2) + k * (4.5 * (nxx + nyy - 2.0 * nxy - tr) + 4.5 * a1p1 - 4.5 * a1p2 + 4.5 * a1m1 + 4.5 * a1m2));
  let cu11 = ux + uz;
  f11 = 0.0277777777777778 * (rho * (1.0 + 3.0 * cu11 + 4.5 * cu11 * cu11 - usq + 4.5 * a0p2 + 4.5 * a0p3 + 4.5 * a0m2 - 4.5 * a0m3) + k * (4.5 * (nxx + nzz + 2.0 * nxz - tr) + 4.5 * a1p2 + 4.5 * a1p3 + 4.5 * a1m2 - 4.5 * a1m3));
  let cu12 = -ux - uz;
  f12 = 0.0277777777777778 * (rho * (1.0 + 3.0 * cu12 + 4.5 * cu12 * cu12 - usq - 4.5 * a0p2 - 4.5 * a0p3 - 4.5 * a0m2 + 4.5 * a0m3) + k * (4.5 * (nxx + nzz + 2.0 * nxz - tr) - 4.5 * a1p2 - 4.5 * a1p3 - 4.5 * a1m2 + 4.5 * a1m3));
  let cu13 = ux - uz;
  f13 = 0.0277777777777778 * (rho * (1.0 + 3.0 * cu13 + 4.5 * cu13 * cu13 - usq + 4.5 * a0p2 - 4.5 * a0p3 + 4.5 * a0m2 + 4.5 * a0m3) + k * (4.5 * (nxx + nzz - 2.0 * nxz - tr) + 4.5 * a1p2 - 4.5 * a1p3 + 4.5 * a1m2 + 4.5 * a1m3));
  let cu14 = -ux + uz;
  f14 = 0.0277777777777778 * (rho * (1.0 + 3.0 * cu14 + 4.5 * cu14 * cu14 - usq - 4.5 * a0p2 + 4.5 * a0p3 - 4.5 * a0m2 - 4.5 * a0m3) + k * (4.5 * (nxx + nzz - 2.0 * nxz - tr) - 4.5 * a1p2 + 4.5 * a1p3 - 4.5 * a1m2 - 4.5 * a1m3));
  let cu15 = uy + uz;
  f15 = 0.0277777777777778 * (rho * (1.0 + 3.0 * cu15 + 4.5 * cu15 * cu15 - usq + 4.5 * a0p1 + 4.5 * a0p3 - 4.5 * a0m1 + 4.5 * a0m3) + k * (4.5 * (nyy + nzz + 2.0 * nyz - tr) + 4.5 * a1p1 + 4.5 * a1p3 - 4.5 * a1m1 + 4.5 * a1m3));
  let cu16 = -uy - uz;
  f16 = 0.0277777777777778 * (rho * (1.0 + 3.0 * cu16 + 4.5 * cu16 * cu16 - usq - 4.5 * a0p1 - 4.5 * a0p3 + 4.5 * a0m1 - 4.5 * a0m3) + k * (4.5 * (nyy + nzz + 2.0 * nyz - tr) - 4.5 * a1p1 - 4.5 * a1p3 + 4.5 * a1m1 - 4.5 * a1m3));
  let cu17 = uy - uz;
  f17 = 0.0277777777777778 * (rho * (1.0 + 3.0 * cu17 + 4.5 * cu17 * cu17 - usq + 4.5 * a0p1 - 4.5 * a0p3 - 4.5 * a0m1 - 4.5 * a0m3) + k * (4.5 * (nyy + nzz - 2.0 * nyz - tr) + 4.5 * a1p1 - 4.5 * a1p3 - 4.5 * a1m1 - 4.5 * a1m3));
  let cu18 = -uy + uz;
  f18 = 0.0277777777777778 * (rho * (1.0 + 3.0 * cu18 + 4.5 * cu18 * cu18 - usq - 4.5 * a0p1 + 4.5 * a0p3 + 4.5 * a0m1 + 4.5 * a0m3) + k * (4.5 * (nyy + nzz - 2.0 * nyz - tr) - 4.5 * a1p1 + 4.5 * a1p3 + 4.5 * a1m1 + 4.5 * a1m3));
  (*f)[0] = f0;
  (*f)[1] = f1;
  (*f)[2] = f2;
  (*f)[3] = f3;
  (*f)[4] = f4;
  (*f)[5] = f5;
  (*f)[6] = f6;
  (*f)[7] = f7;
  (*f)[8] = f8;
  (*f)[9] = f9;
  (*f)[10] = f10;
  (*f)[11] = f11;
  (*f)[12] = f12;
  (*f)[13] = f13;
  (*f)[14] = f14;
  (*f)[15] = f15;
  (*f)[16] = f16;
  (*f)[17] = f17;
  (*f)[18] = f18;
  return vec4<f32>(rho, ux, uy, uz);
}

fn collide_bgk(f: ptr<function, array<f32, 19>>, tau0: f32, smag: f32, tauMin: f32) -> vec4<f32> {
  var f0 = (*f)[0];
  var f1 = (*f)[1];
  var f2 = (*f)[2];
  var f3 = (*f)[3];
  var f4 = (*f)[4];
  var f5 = (*f)[5];
  var f6 = (*f)[6];
  var f7 = (*f)[7];
  var f8 = (*f)[8];
  var f9 = (*f)[9];
  var f10 = (*f)[10];
  var f11 = (*f)[11];
  var f12 = (*f)[12];
  var f13 = (*f)[13];
  var f14 = (*f)[14];
  var f15 = (*f)[15];
  var f16 = (*f)[16];
  var f17 = (*f)[17];
  var f18 = (*f)[18];
  let rho = f0 + f1 + f2 + f3 + f4 + f5 + f6 + f7 + f8 + f9 + f10 + f11 + f12 + f13 + f14 + f15 + f16 + f17 + f18;
  let ir = 1.0 / rho;
  let ux = (f1 + f7 + f9 + f11 + f13 - f2 - f8 - f10 - f12 - f14) * ir;
  let uy = (f3 + f7 + f10 + f15 + f17 - f4 - f8 - f9 - f16 - f18) * ir;
  let uz = (f5 + f11 + f14 + f15 + f18 - f6 - f12 - f13 - f16 - f17) * ir;
  let nxx = f1 + f2 + f7 + f8 + f9 + f10 + f11 + f12 + f13 + f14 - rho * (ux * ux + 0.333333333333333);
  let nyy = f3 + f4 + f7 + f8 + f9 + f10 + f15 + f16 + f17 + f18 - rho * (uy * uy + 0.333333333333333);
  let nzz = f5 + f6 + f11 + f12 + f13 + f14 + f15 + f16 + f17 + f18 - rho * (uz * uz + 0.333333333333333);
  let nxy = f7 + f8 - f9 - f10 - rho * ux * uy;
  let nxz = f11 + f12 - f13 - f14 - rho * ux * uz;
  let nyz = f15 + f16 - f17 - f18 - rho * uy * uz;
  let qn = sqrt(nxx * nxx + nyy * nyy + nzz * nzz + 2.0 * (nxy * nxy + nxz * nxz + nyz * nyz));
  let tau = max(0.5 * (tau0 + sqrt(tau0 * tau0 + smag * qn * ir)), tauMin);
  let om = 1.0 / tau;
  let usq = 1.5 * (ux * ux + uy * uy + uz * uz);
  let k = 1.0 - om;
  let cu0 = 0.0;
  f0 = k * f0 + om * 0.333333333333333 * rho * (1.0 + 3.0 * cu0 + 4.5 * cu0 * cu0 - usq);
  let cu1 = ux;
  f1 = k * f1 + om * 0.0555555555555556 * rho * (1.0 + 3.0 * cu1 + 4.5 * cu1 * cu1 - usq);
  let cu2 = -ux;
  f2 = k * f2 + om * 0.0555555555555556 * rho * (1.0 + 3.0 * cu2 + 4.5 * cu2 * cu2 - usq);
  let cu3 = uy;
  f3 = k * f3 + om * 0.0555555555555556 * rho * (1.0 + 3.0 * cu3 + 4.5 * cu3 * cu3 - usq);
  let cu4 = -uy;
  f4 = k * f4 + om * 0.0555555555555556 * rho * (1.0 + 3.0 * cu4 + 4.5 * cu4 * cu4 - usq);
  let cu5 = uz;
  f5 = k * f5 + om * 0.0555555555555556 * rho * (1.0 + 3.0 * cu5 + 4.5 * cu5 * cu5 - usq);
  let cu6 = -uz;
  f6 = k * f6 + om * 0.0555555555555556 * rho * (1.0 + 3.0 * cu6 + 4.5 * cu6 * cu6 - usq);
  let cu7 = ux + uy;
  f7 = k * f7 + om * 0.0277777777777778 * rho * (1.0 + 3.0 * cu7 + 4.5 * cu7 * cu7 - usq);
  let cu8 = -ux - uy;
  f8 = k * f8 + om * 0.0277777777777778 * rho * (1.0 + 3.0 * cu8 + 4.5 * cu8 * cu8 - usq);
  let cu9 = ux - uy;
  f9 = k * f9 + om * 0.0277777777777778 * rho * (1.0 + 3.0 * cu9 + 4.5 * cu9 * cu9 - usq);
  let cu10 = -ux + uy;
  f10 = k * f10 + om * 0.0277777777777778 * rho * (1.0 + 3.0 * cu10 + 4.5 * cu10 * cu10 - usq);
  let cu11 = ux + uz;
  f11 = k * f11 + om * 0.0277777777777778 * rho * (1.0 + 3.0 * cu11 + 4.5 * cu11 * cu11 - usq);
  let cu12 = -ux - uz;
  f12 = k * f12 + om * 0.0277777777777778 * rho * (1.0 + 3.0 * cu12 + 4.5 * cu12 * cu12 - usq);
  let cu13 = ux - uz;
  f13 = k * f13 + om * 0.0277777777777778 * rho * (1.0 + 3.0 * cu13 + 4.5 * cu13 * cu13 - usq);
  let cu14 = -ux + uz;
  f14 = k * f14 + om * 0.0277777777777778 * rho * (1.0 + 3.0 * cu14 + 4.5 * cu14 * cu14 - usq);
  let cu15 = uy + uz;
  f15 = k * f15 + om * 0.0277777777777778 * rho * (1.0 + 3.0 * cu15 + 4.5 * cu15 * cu15 - usq);
  let cu16 = -uy - uz;
  f16 = k * f16 + om * 0.0277777777777778 * rho * (1.0 + 3.0 * cu16 + 4.5 * cu16 * cu16 - usq);
  let cu17 = uy - uz;
  f17 = k * f17 + om * 0.0277777777777778 * rho * (1.0 + 3.0 * cu17 + 4.5 * cu17 * cu17 - usq);
  let cu18 = -uy + uz;
  f18 = k * f18 + om * 0.0277777777777778 * rho * (1.0 + 3.0 * cu18 + 4.5 * cu18 * cu18 - usq);
  (*f)[0] = f0;
  (*f)[1] = f1;
  (*f)[2] = f2;
  (*f)[3] = f3;
  (*f)[4] = f4;
  (*f)[5] = f5;
  (*f)[6] = f6;
  (*f)[7] = f7;
  (*f)[8] = f8;
  (*f)[9] = f9;
  (*f)[10] = f10;
  (*f)[11] = f11;
  (*f)[12] = f12;
  (*f)[13] = f13;
  (*f)[14] = f14;
  (*f)[15] = f15;
  (*f)[16] = f16;
  (*f)[17] = f17;
  (*f)[18] = f18;
  return vec4<f32>(rho, ux, uy, uz);
}

fn equilibrium_rr(f: ptr<function, array<f32, 19>>, rho: f32, ux: f32, uy: f32, uz: f32) {
  let usq = 1.5 * (ux * ux + uy * uy + uz * uz);
  let a0p1 = ux * ux * uy + uy * uz * uz;
  let a0p2 = ux * uz * uz + ux * uy * uy;
  let a0p3 = uy * uy * uz + ux * ux * uz;
  let a0m1 = ux * ux * uy - uy * uz * uz;
  let a0m2 = ux * uz * uz - ux * uy * uy;
  let a0m3 = uy * uy * uz - ux * ux * uz;
  (*f)[0] = 0.333333333333333 * rho * (1.0 + 3.0 * (0.0) + 4.5 * (0.0) * (0.0) - usq);
  (*f)[1] = 0.0555555555555556 * rho * (1.0 + 3.0 * (ux) + 4.5 * (ux) * (ux) - usq - 9.0 * a0p2);
  (*f)[2] = 0.0555555555555556 * rho * (1.0 + 3.0 * (-ux) + 4.5 * (-ux) * (-ux) - usq + 9.0 * a0p2);
  (*f)[3] = 0.0555555555555556 * rho * (1.0 + 3.0 * (uy) + 4.5 * (uy) * (uy) - usq - 9.0 * a0p1);
  (*f)[4] = 0.0555555555555556 * rho * (1.0 + 3.0 * (-uy) + 4.5 * (-uy) * (-uy) - usq + 9.0 * a0p1);
  (*f)[5] = 0.0555555555555556 * rho * (1.0 + 3.0 * (uz) + 4.5 * (uz) * (uz) - usq - 9.0 * a0p3);
  (*f)[6] = 0.0555555555555556 * rho * (1.0 + 3.0 * (-uz) + 4.5 * (-uz) * (-uz) - usq + 9.0 * a0p3);
  (*f)[7] = 0.0277777777777778 * rho * (1.0 + 3.0 * (ux + uy) + 4.5 * (ux + uy) * (ux + uy) - usq + 4.5 * a0p1 + 4.5 * a0p2 + 4.5 * a0m1 - 4.5 * a0m2);
  (*f)[8] = 0.0277777777777778 * rho * (1.0 + 3.0 * (-ux - uy) + 4.5 * (-ux - uy) * (-ux - uy) - usq - 4.5 * a0p1 - 4.5 * a0p2 - 4.5 * a0m1 + 4.5 * a0m2);
  (*f)[9] = 0.0277777777777778 * rho * (1.0 + 3.0 * (ux - uy) + 4.5 * (ux - uy) * (ux - uy) - usq - 4.5 * a0p1 + 4.5 * a0p2 - 4.5 * a0m1 - 4.5 * a0m2);
  (*f)[10] = 0.0277777777777778 * rho * (1.0 + 3.0 * (-ux + uy) + 4.5 * (-ux + uy) * (-ux + uy) - usq + 4.5 * a0p1 - 4.5 * a0p2 + 4.5 * a0m1 + 4.5 * a0m2);
  (*f)[11] = 0.0277777777777778 * rho * (1.0 + 3.0 * (ux + uz) + 4.5 * (ux + uz) * (ux + uz) - usq + 4.5 * a0p2 + 4.5 * a0p3 + 4.5 * a0m2 - 4.5 * a0m3);
  (*f)[12] = 0.0277777777777778 * rho * (1.0 + 3.0 * (-ux - uz) + 4.5 * (-ux - uz) * (-ux - uz) - usq - 4.5 * a0p2 - 4.5 * a0p3 - 4.5 * a0m2 + 4.5 * a0m3);
  (*f)[13] = 0.0277777777777778 * rho * (1.0 + 3.0 * (ux - uz) + 4.5 * (ux - uz) * (ux - uz) - usq + 4.5 * a0p2 - 4.5 * a0p3 + 4.5 * a0m2 + 4.5 * a0m3);
  (*f)[14] = 0.0277777777777778 * rho * (1.0 + 3.0 * (-ux + uz) + 4.5 * (-ux + uz) * (-ux + uz) - usq - 4.5 * a0p2 + 4.5 * a0p3 - 4.5 * a0m2 - 4.5 * a0m3);
  (*f)[15] = 0.0277777777777778 * rho * (1.0 + 3.0 * (uy + uz) + 4.5 * (uy + uz) * (uy + uz) - usq + 4.5 * a0p1 + 4.5 * a0p3 - 4.5 * a0m1 + 4.5 * a0m3);
  (*f)[16] = 0.0277777777777778 * rho * (1.0 + 3.0 * (-uy - uz) + 4.5 * (-uy - uz) * (-uy - uz) - usq - 4.5 * a0p1 - 4.5 * a0p3 + 4.5 * a0m1 - 4.5 * a0m3);
  (*f)[17] = 0.0277777777777778 * rho * (1.0 + 3.0 * (uy - uz) + 4.5 * (uy - uz) * (uy - uz) - usq + 4.5 * a0p1 - 4.5 * a0p3 - 4.5 * a0m1 - 4.5 * a0m3);
  (*f)[18] = 0.0277777777777778 * rho * (1.0 + 3.0 * (-uy + uz) + 4.5 * (-uy + uz) * (-uy + uz) - usq - 4.5 * a0p1 + 4.5 * a0p3 + 4.5 * a0m1 + 4.5 * a0m3);
}

fn equilibrium_bgk(f: ptr<function, array<f32, 19>>, rho: f32, ux: f32, uy: f32, uz: f32) {
  let usq = 1.5 * (ux * ux + uy * uy + uz * uz);
  (*f)[0] = 0.333333333333333 * rho * (1.0 + 3.0 * (0.0) + 4.5 * (0.0) * (0.0) - usq);
  (*f)[1] = 0.0555555555555556 * rho * (1.0 + 3.0 * (ux) + 4.5 * (ux) * (ux) - usq);
  (*f)[2] = 0.0555555555555556 * rho * (1.0 + 3.0 * (-ux) + 4.5 * (-ux) * (-ux) - usq);
  (*f)[3] = 0.0555555555555556 * rho * (1.0 + 3.0 * (uy) + 4.5 * (uy) * (uy) - usq);
  (*f)[4] = 0.0555555555555556 * rho * (1.0 + 3.0 * (-uy) + 4.5 * (-uy) * (-uy) - usq);
  (*f)[5] = 0.0555555555555556 * rho * (1.0 + 3.0 * (uz) + 4.5 * (uz) * (uz) - usq);
  (*f)[6] = 0.0555555555555556 * rho * (1.0 + 3.0 * (-uz) + 4.5 * (-uz) * (-uz) - usq);
  (*f)[7] = 0.0277777777777778 * rho * (1.0 + 3.0 * (ux + uy) + 4.5 * (ux + uy) * (ux + uy) - usq);
  (*f)[8] = 0.0277777777777778 * rho * (1.0 + 3.0 * (-ux - uy) + 4.5 * (-ux - uy) * (-ux - uy) - usq);
  (*f)[9] = 0.0277777777777778 * rho * (1.0 + 3.0 * (ux - uy) + 4.5 * (ux - uy) * (ux - uy) - usq);
  (*f)[10] = 0.0277777777777778 * rho * (1.0 + 3.0 * (-ux + uy) + 4.5 * (-ux + uy) * (-ux + uy) - usq);
  (*f)[11] = 0.0277777777777778 * rho * (1.0 + 3.0 * (ux + uz) + 4.5 * (ux + uz) * (ux + uz) - usq);
  (*f)[12] = 0.0277777777777778 * rho * (1.0 + 3.0 * (-ux - uz) + 4.5 * (-ux - uz) * (-ux - uz) - usq);
  (*f)[13] = 0.0277777777777778 * rho * (1.0 + 3.0 * (ux - uz) + 4.5 * (ux - uz) * (ux - uz) - usq);
  (*f)[14] = 0.0277777777777778 * rho * (1.0 + 3.0 * (-ux + uz) + 4.5 * (-ux + uz) * (-ux + uz) - usq);
  (*f)[15] = 0.0277777777777778 * rho * (1.0 + 3.0 * (uy + uz) + 4.5 * (uy + uz) * (uy + uz) - usq);
  (*f)[16] = 0.0277777777777778 * rho * (1.0 + 3.0 * (-uy - uz) + 4.5 * (-uy - uz) * (-uy - uz) - usq);
  (*f)[17] = 0.0277777777777778 * rho * (1.0 + 3.0 * (uy - uz) + 4.5 * (uy - uz) * (uy - uz) - usq);
  (*f)[18] = 0.0277777777777778 * rho * (1.0 + 3.0 * (-uy + uz) + 4.5 * (-uy + uz) * (-uy + uz) - usq);
}

// third-order coefficients per direction: 13.5 x (H_xxy + H_yzz, H_xzz + H_xyy, H_yyz + H_xxz), 4.5 x the differences
const P3C: array<array<f32, 6>, 19> = array<array<f32, 6>, 19>(
  array<f32, 6>(0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
  array<f32, 6>(0.0, -9.0, 0.0, 0.0, 0.0, 0.0),
  array<f32, 6>(0.0, 9.0, 0.0, 0.0, 0.0, 0.0),
  array<f32, 6>(-9.0, 0.0, 0.0, 0.0, 0.0, 0.0),
  array<f32, 6>(9.0, 0.0, 0.0, 0.0, 0.0, 0.0),
  array<f32, 6>(0.0, 0.0, -9.0, 0.0, 0.0, 0.0),
  array<f32, 6>(0.0, 0.0, 9.0, 0.0, 0.0, 0.0),
  array<f32, 6>(4.5, 4.5, 0.0, 4.5, -4.5, 0.0),
  array<f32, 6>(-4.5, -4.5, 0.0, -4.5, 4.5, 0.0),
  array<f32, 6>(-4.5, 4.5, 0.0, -4.5, -4.5, 0.0),
  array<f32, 6>(4.5, -4.5, 0.0, 4.5, 4.5, 0.0),
  array<f32, 6>(0.0, 4.5, 4.5, 0.0, 4.5, -4.5),
  array<f32, 6>(0.0, -4.5, -4.5, 0.0, -4.5, 4.5),
  array<f32, 6>(0.0, 4.5, -4.5, 0.0, 4.5, 4.5),
  array<f32, 6>(0.0, -4.5, 4.5, 0.0, -4.5, -4.5),
  array<f32, 6>(4.5, 0.0, 4.5, -4.5, 0.0, 4.5),
  array<f32, 6>(-4.5, 0.0, -4.5, 4.5, 0.0, -4.5),
  array<f32, 6>(4.5, 0.0, -4.5, -4.5, 0.0, -4.5),
  array<f32, 6>(-4.5, 0.0, 4.5, 4.5, 0.0, 4.5));
