// Generates the unrolled collision and streaming code of the v1 flow engine from the lattice
// tables in src/cfd/flow.js, for its three implementations:
//   src/cfd/flow-kernel.js            JavaScript (CPU engine's fast path)
//   native/shaders/flow_gen.wgsl      WGSL (GPU engine, web and native)
//   native/src/cfd/flow_kernel.inc    C++ (native CPU engine)
// Run after changing the collision model: node scripts/gen-flow.mjs
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { CX, CY, CZ, W, P3 } from '../src/cfd/flow.js';

const root = path.resolve(import.meta.dirname, '..');
const HEADER = 'Generated by scripts/gen-flow.mjs from src/cfd/flow.js - do not edit.';

// a number as a literal for each language
const lit = (v, lang) => {
  // coefficients are simple fractions: print them exactly (4.5, not 4.499999999999999)
  let s = Number.isInteger(v) ? `${v}.0` : String(+v.toPrecision(15));
  if (!s.includes('.') && !s.includes('e')) s += '.0';
  return lang === 'cpp' ? `${s}f` : s;
};
// sum of terms with integer or real coefficients: [[coef, expr], ...]
function sum(terms, lang) {
  let out = '';
  for (const [c, e] of terms) {
    if (Math.abs(c) < 1e-12) continue;
    const neg = c < 0, a = Math.abs(c);
    const t = Math.abs(a - 1) < 1e-12 ? e : `${lit(a, lang)} * ${e}`;
    out += out ? (neg ? ` - ${t}` : ` + ${t}`) : neg ? `-${t}` : t;
  }
  return out || lit(0, lang);
}
const f = (i) => `f${i}`;
const dirs = [...Array(19).keys()];
const byC = (sel, sign) => dirs.filter((i) => sel(i) === sign);

/** Statements that turn f0..f18 into their post-collision values; rho, ux, uy, uz stay defined. */
function collide(lang, rr) {
  const T = lang === 'wgsl' ? 'let' : lang === 'js' ? 'const' : 'const float';
  const V = lang === 'wgsl' ? 'var' : lang === 'js' ? 'let' : 'float';
  const sqrt = lang === 'cpp' ? 'std::sqrt' : lang === 'js' ? 'Math.sqrt' : 'sqrt';
  const max = lang === 'cpp' ? 'std::max' : lang === 'js' ? 'Math.max' : 'max';
  const L = [];
  const mom = (sel) => sum([...byC(sel, 1).map((i) => [1, f(i)]), ...byC(sel, -1).map((i) => [-1, f(i)])], lang);
  const sq = (sel) => sum(dirs.filter((i) => sel(i) !== 0).map((i) => [1, f(i)]), lang);
  L.push(`${T} rho = ${dirs.map(f).join(' + ')};`);
  L.push(`${T} ir = ${lit(1, lang)} / rho;`);
  L.push(`${T} ux = (${mom((i) => CX[i])}) * ir;`);
  L.push(`${T} uy = (${mom((i) => CY[i])}) * ir;`);
  L.push(`${T} uz = (${mom((i) => CZ[i])}) * ir;`);
  const third = lit(1 / 3, lang);
  L.push(`${T} nxx = ${sq((i) => CX[i])} - rho * (ux * ux + ${third});`);
  L.push(`${T} nyy = ${sq((i) => CY[i])} - rho * (uy * uy + ${third});`);
  L.push(`${T} nzz = ${sq((i) => CZ[i])} - rho * (uz * uz + ${third});`);
  L.push(`${T} nxy = ${mom((i) => CX[i] * CY[i])} - rho * ux * uy;`);
  L.push(`${T} nxz = ${mom((i) => CX[i] * CZ[i])} - rho * ux * uz;`);
  L.push(`${T} nyz = ${mom((i) => CY[i] * CZ[i])} - rho * uy * uz;`);
  L.push(`${T} qn = ${sqrt}(nxx * nxx + nyy * nyy + nzz * nzz + ${lit(2, lang)} * (nxy * nxy + nxz * nxz + nyz * nyz));`);
  L.push(`${T} tau = ${max}(${lit(0.5, lang)} * (tau0 + ${sqrt}(tau0 * tau0 + smag * qn * ir)), tauMin);`);
  L.push(`${T} om = ${lit(1, lang)} / tau;`);
  L.push(`${T} usq = ${lit(1.5, lang)} * (ux * ux + uy * uy + uz * uz);`);
  const cu = (i) => sum([[CX[i], 'ux'], [CY[i], 'uy'], [CZ[i], 'uz']], lang);
  if (!rr) {
    L.push(`${T} k = ${lit(1, lang)} - om;`);
    for (const i of dirs) {
      L.push(i === 0 ? `${T} cu0 = ${lit(0, lang)};` : `${T} cu${i} = ${cu(i)};`);
      L.push(`${f(i)} = k * ${f(i)} + om * ${lit(W[i], lang)} * rho * (${lit(1, lang)} + ${lit(3, lang)} * cu${i} + ${lit(4.5, lang)} * cu${i} * cu${i} - usq);`);
    }
    return L;
  }
  L.push(`${T} k = ${lit(1, lang)} - om;`);
  L.push(`${T} a0p1 = ux * ux * uy + uy * uz * uz;`);
  L.push(`${T} a0p2 = ux * uz * uz + ux * uy * uy;`);
  L.push(`${T} a0p3 = uy * uy * uz + ux * ux * uz;`);
  L.push(`${T} a0m1 = ux * ux * uy - uy * uz * uz;`);
  L.push(`${T} a0m2 = ux * uz * uz - ux * uy * uy;`);
  L.push(`${T} a0m3 = uy * uy * uz - ux * ux * uz;`);
  L.push(`${T} txxy = ${lit(2, lang)} * ux * nxy + uy * nxx;`);
  L.push(`${T} tyzz = ${lit(2, lang)} * uz * nyz + uy * nzz;`);
  L.push(`${T} txzz = ${lit(2, lang)} * uz * nxz + ux * nzz;`);
  L.push(`${T} txyy = ${lit(2, lang)} * uy * nxy + ux * nyy;`);
  L.push(`${T} tyyz = ${lit(2, lang)} * uy * nyz + uz * nyy;`);
  L.push(`${T} txxz = ${lit(2, lang)} * ux * nxz + uz * nxx;`);
  L.push(`${T} a1p1 = txxy + tyzz;`, `${T} a1p2 = txzz + txyy;`, `${T} a1p3 = tyyz + txxz;`);
  L.push(`${T} a1m1 = txxy - tyzz;`, `${T} a1m2 = txzz - txyy;`, `${T} a1m3 = tyyz - txxz;`);
  L.push(`${T} tr = ${lit(1 / 3, lang)} * (nxx + nyy + nzz);`);
  const a0 = ['a0p1', 'a0p2', 'a0p3', 'a0m1', 'a0m2', 'a0m3'], a1 = ['a1p1', 'a1p2', 'a1p3', 'a1m1', 'a1m2', 'a1m3'];
  for (const i of dirs) {
    const cx = CX[i], cy = CY[i], cz = CZ[i], p = P3[i];
    const c3 = p.map((v, j) => (j < 3 ? 13.5 : 4.5) * v);
    const t3e = sum(c3.map((c, j) => [c, a0[j]]), lang);
    const t3n = sum(c3.map((c, j) => [c, a1[j]]), lang);
    const h2 = sum([[cx * cx, 'nxx'], [cy * cy, 'nyy'], [cz * cz, 'nzz'], [2 * cx * cy, 'nxy'], [2 * cx * cz, 'nxz'], [2 * cy * cz, 'nyz'], [-1, 'tr']], lang);
    const cuv = i === 0 ? null : cu(i);
    if (cuv) L.push(`${T} cu${i} = ${cuv};`);
    const eq = cuv ? `${lit(1, lang)} + ${lit(3, lang)} * cu${i} + ${lit(4.5, lang)} * cu${i} * cu${i} - usq` : `${lit(1, lang)} - usq`;
    const plus = (t) => (t === lit(0, lang) ? '' : t.startsWith('-') ? ` - ${t.slice(1)}` : ` + ${t}`);
    L.push(`${f(i)} = ${lit(W[i], lang)} * (rho * (${eq}${plus(t3e)}) + k * (${lit(4.5, lang)} * (${h2})${plus(t3n)}));`);
  }
  void V;
  return L;
}

// ---------- JavaScript: runs of bulk cells along x ----------

function jsRun(rr, odd) {
  const name = `bulkRun${rr ? 'RR' : 'BGK'}${odd ? 'Odd' : 'Even'}`;
  const L = [];
  L.push(`/** Bulk cells c0 <= n < c1 of one row; o[i] = offset of the neighbour n + c_i (odd i). */`);
  L.push(`export function ${name}(F, N, c0, c1, o, tau0, smag) {`);
  L.push('  const tauMin = 0;');
  const offs = [];
  for (let i = 1; i < 19; i += 2) offs.push(`o${i} = o[${i}]`);
  L.push(`  const ${offs.join(', ')};`);
  const bases = [];
  for (let d = 0; d < 19; d++) bases.push(`b${d} = ${d} * N`);
  L.push(`  const ${bases.join(', ')};`);
  L.push('  for (let n = c0; n < c1; n++) {');
  L.push('    let f0 = F[n];');
  for (let i = 1; i < 19; i += 2) {
    if (odd) L.push(`    let f${i} = F[b${i} + n], f${i + 1} = F[b${i + 1} + n + o${i}];`);
    else L.push(`    let f${i} = F[b${i + 1} + n], f${i + 1} = F[b${i} + n + o${i}];`);
  }
  for (const s of collide('js', rr)) L.push(`    ${s}`);
  L.push('    F[n] = f0;');
  for (let i = 1; i < 19; i += 2) {
    if (odd) L.push(`    F[b${i + 1} + n + o${i}] = f${i}; F[b${i} + n] = f${i + 1};`);
    else L.push(`    F[b${i} + n + o${i}] = f${i}; F[b${i + 1} + n] = f${i + 1};`);
  }
  L.push('  }');
  L.push('}');
  return L.join('\n');
}

const js = [`// ${HEADER}`, '// The CPU engine\'s fast path (flow-cpu.js): bulk fluid cells, in-place streaming, unrolled.', '/* eslint-disable */', ''];
for (const rr of [true, false]) for (const odd of [false, true]) js.push(jsRun(rr, odd), '');
writeFileSync(path.join(root, 'src/cfd/flow-kernel.js'), js.join('\n'));

// ---------- WGSL: collision functions on f[19] ----------

function wgslCollide(rr) {
  const L = [`fn collide_${rr ? 'rr' : 'bgk'}(f: ptr<function, array<f32, 19>>, tau0: f32, smag: f32, tauMin: f32) -> vec4<f32> {`];
  for (let i = 0; i < 19; i++) L.push(`  var f${i} = (*f)[${i}];`);
  for (const s of collide('wgsl', rr)) L.push(`  ${s}`);
  for (let i = 0; i < 19; i++) L.push(`  (*f)[${i}] = f${i};`);
  L.push('  return vec4<f32>(rho, ux, uy, uz);', '}');
  return L.join('\n');
}
function wgslEquilibrium(rr) {
  const L = [`fn equilibrium_${rr ? 'rr' : 'bgk'}(f: ptr<function, array<f32, 19>>, rho: f32, ux: f32, uy: f32, uz: f32) {`];
  L.push('  let usq = 1.5 * (ux * ux + uy * uy + uz * uz);');
  if (rr) {
    L.push('  let a0p1 = ux * ux * uy + uy * uz * uz;', '  let a0p2 = ux * uz * uz + ux * uy * uy;', '  let a0p3 = uy * uy * uz + ux * ux * uz;');
    L.push('  let a0m1 = ux * ux * uy - uy * uz * uz;', '  let a0m2 = ux * uz * uz - ux * uy * uy;', '  let a0m3 = uy * uy * uz - ux * ux * uz;');
  }
  const a0 = ['a0p1', 'a0p2', 'a0p3', 'a0m1', 'a0m2', 'a0m3'];
  for (let i = 0; i < 19; i++) {
    const cu = sum([[CX[i], 'ux'], [CY[i], 'uy'], [CZ[i], 'uz']], 'wgsl');
    const t3e = rr ? sum(P3[i].map((v, j) => [(j < 3 ? 13.5 : 4.5) * v, a0[j]]), 'wgsl') : '0.0';
    const t3 = t3e === '0.0' ? '' : t3e.startsWith('-') ? ` - ${t3e.slice(1)}` : ` + ${t3e}`;
    L.push(`  (*f)[${i}] = ${lit(W[i], 'wgsl')} * rho * (1.0 + 3.0 * (${cu}) + 4.5 * (${cu}) * (${cu}) - usq${t3});`);
  }
  L.push('}');
  return L.join('\n');
}
const wgsl = [`// ${HEADER}`, '// Collision models of the v1 flow engine (flow.wgsl): post-collision populations in place,', '// returning (rho, ux, uy, uz).', ''];
wgsl.push(wgslCollide(true), '', wgslCollide(false), '', wgslEquilibrium(true), '', wgslEquilibrium(false), '');
// the third-order terms' coefficients per direction: 13.5 P+ and 4.5 P- (flow.js P3)
const p3c = P3.map((p) => `array<f32, 6>(${p.map((v, j) => lit((j < 3 ? 13.5 : 4.5) * v, 'wgsl')).join(', ')})`);
wgsl.push('// third-order coefficients per direction: 13.5 x (H_xxy + H_yzz, H_xzz + H_xyy, H_yyz + H_xxz), 4.5 x the differences');
wgsl.push(`const P3C: array<array<f32, 6>, 19> = array<array<f32, 6>, 19>(\n  ${p3c.join(',\n  ')});`, '');
writeFileSync(path.join(root, 'native/shaders/flow_gen.wgsl'), wgsl.join('\n'));

// ---------- C++: runs of bulk cells along x (vectorizable) ----------

function cppRun(rr, odd) {
  const L = [];
  L.push(`template <> inline void bulkRun<${rr}, ${odd}>(float* __restrict F, int64_t N, int64_t c0, int64_t c1, const int64_t* o, float tau0, float smag) {`);
  L.push('    const float tauMin = 0.0f;');
  for (let d = 0; d < 19; d++) L.push(`    float* __restrict F${d} = F + ${d} * N;`);
  for (let i = 1; i < 19; i += 2) L.push(`    const int64_t o${i} = o[${i}];`);
  L.push('#if defined(__clang__)', '#pragma clang loop vectorize(enable) interleave(disable)', '#endif');
  L.push('    for (int64_t n = c0; n < c1; n++) {');
  L.push('        float f0 = F0[n];');
  for (let i = 1; i < 19; i += 2) {
    if (odd) L.push(`        float f${i} = F${i}[n], f${i + 1} = F${i + 1}[n + o${i}];`);
    else L.push(`        float f${i} = F${i + 1}[n], f${i + 1} = F${i}[n + o${i}];`);
  }
  for (const s of collide('cpp', rr)) L.push(`        ${s}`);
  L.push('        F0[n] = f0;');
  for (let i = 1; i < 19; i += 2) {
    if (odd) L.push(`        F${i + 1}[n + o${i}] = f${i}; F${i}[n] = f${i + 1};`);
    else L.push(`        F${i}[n + o${i}] = f${i}; F${i + 1}[n] = f${i + 1};`);
  }
  L.push('    }', '}');
  return L.join('\n');
}
const cpp = [`// ${HEADER}`, '// The native CPU engine\'s fast path (flow_cpu.cpp): bulk fluid cells, in-place streaming, unrolled.', '// Included inside namespace ps::flow after the primary template bulkRun<RR, Odd>.', ''];
for (const rr of [true, false]) for (const odd of [false, true]) cpp.push(cppRun(rr, odd), '');
writeFileSync(path.join(root, 'native/src/cfd/flow_kernel.inc'), cpp.join('\n'));
console.log('Wrote src/cfd/flow-kernel.js, native/shaders/flow_gen.wgsl, native/src/cfd/flow_kernel.inc');
